# Generated by Django 4.1.2 on 2022-10-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('file', models.FileField(upload_to='uploads/')),
                ('picture', models.ImageField(upload_to='')),
            ],
        ),
    ]
